### ISSUE TITLE
Clarification on meta data for "ITEM_ID"

### ISSUE THREAD

**Issue by korlan-rayong** [kaogeek/thailand-budget-pdf2csv#14]
As the format of ITEM_ID is xxxx.x.x.xx, can you make it clear in the metadata which section refers to REF_DOC and which one refer to RUNNING_NO? Or maybe clarify each section means if possible. Thx.

**Comment by tee4cute** [comment]
Hi @korlan-rayong 

As shown in repo `README.md` file, and also in "META" sheet in the spreadsheet as well,

<img width="866" alt="Screen Shot 2564-07-25 at 11 27 03" src="https://user-images.githubusercontent.com/4979546/126887749-b90c6a22-c928-4dab-ad53-ff1daa45b669.png">

You can see that the `ITEM_ID` is in format `[REF_DOC].[RUNNING_NO]`.

And, for about the `REF_DOC`, it is in format `[FY].[เล่ม].[ฉบับ]` (three chunks of dot notation).

So, the first three chunks of `ITEM_ID` must refer to its `REF_DOC`, and, the last one would be its `RUNNING_NO`.

Thanks and welcome for your further enquiries krub :)
